[package]
name = "qaccelerator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qip = "0.15.3"
sha2 = "0.10.2"
itertools = "0.10.3"